name: Compare

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Base versions (dep@version, comma-separated) or date"
        default: "webpack@webpack/webpack#master"
        required: true
      current:
        description: "current versions (dep@version, comma-separated) or date"
        default: "webpack@webpack/webpack#master"
        required: true

jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        base:
          - "${{ github.event.inputs.base }}"
        current:
          - "${{ github.event.inputs.current }}"
        case:
          - common-libs
          - esbuild-three
          - rome
        scenario:
          - development-build
          - development-build+initial-persistent-cache
          - development-build+persistent-cache
          - development-rebuild
          - development-rebuild+unsafe-cache
          - production-build
          - production-build+source-map
          - production-build+source-map+babel-env
          - production-build+no-minimize
          - production-build+persistent-cache
          - production-build+initial-persistent-cache
          - production-build+source-map+persistent-cache
          - production-build+source-map+initial-persistent-cache
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.base }} vs ${{ github.event.inputs.current }}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ matrix.case }}-${{ github.event.inputs.base }}
          restore-keys: |
            yarn-${{ matrix.case }}-
            yarn-
      - uses: nick-invision/retry@v2.4.0
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - uses: nick-invision/retry@v2.4.0
        with:
          max_attempts: 3
          timeout_minutes: 25
          command: node bin/compare.js ${{ matrix.case }} ${{ matrix.scenario }} ${{ github.event.inputs.base }} ${{ github.event.inputs.current }}
      - uses: actions/upload-artifact@v2
        with:
          name: compare-results
          path: output
  report:
    needs: [bench]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.base }} vs ${{ github.event.inputs.current }}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-report-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-report-
            yarn-
      - uses: nick-invision/retry@v2.4.0
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - uses: actions/download-artifact@v4.1.7
        with:
          name: compare-results
          path: output
      - run: node bin/report.js
